### ISSUE TITLE
luci无法启动，SSH内手动可以。

### ISSUE THREAD

**Issue by hkthomas** [lmq8267/luci-app-vnt#1]
luci上启动只显示这个，然后就没反应了。

2024-05-23 10:56:08 vnt : 开始启动
2024-05-23 10:56:08 vnt : 找到上传的程序/tmp/vnts，替换为/tmp/vnts 

手动到ssh下去执行就可以正常运行。。LUCI 界面上也会显示出占用信息。

**Comment by lmq8267** [comment]
ssh 执行的是什么 命令？ /etc/init.d/vnt start 吗？

**Comment by hkthomas** [comment]
我直接切换到tmp目录 ./vnts

**Comment by hkthomas** [comment]
/etc/init.d/vnt start  也是没有任何反应跟输出的。

**Comment by lmq8267** [comment]
上传的是什么版本的vnts   要1.2.9.*以上的版本，  1.2.8.*的版本界面就无法启动，参数不一样了

**Comment by hkthomas** [comment]
vnts-mips-unknown-linux-musl-1.2.9.7.tar.gz 上传的这个。

**Comment by hkthomas** [comment]
一开始是自动下载的，没法启动，然后我又手动下了这个传上去的，都不行呢，就很奇怪，是不是init.d里面那个有问题。另一个X86架构的机器又是正常的。

**Comment by lmq8267** [comment]
什么路由器 cpu呢      在路由器管理界面里  状态-系统系统日志里看看 是什么报错

**Comment by hkthomas** [comment]
Thu May 23 11:23:01 2024 daemon.err uhttpd[2236]: sh: /tmp/vnt-cli: not found
Thu May 23 11:23:06 2024 daemon.info vnts[9845]: version: 1.2.9
Thu May 23 11:23:06 2024 daemon.info vnts[9845]: Serial: 2405071448-739
Thu May 23 11:23:06 2024 daemon.err vnts[9845]: error: Found argument '--web-port' which wasn't expected, or isn't valid in this context
Thu May 23 11:23:06 2024 daemon.err vnts[9845]:
Thu May 23 11:23:06 2024 daemon.err vnts[9845]: Usage: vnts <--port <PORT>|--white-token <WHITE_TOKEN>|--gateway <GATEWAY>|--netmask <NETMASK>|--finger|--log-path <LOG_PATH>>
Thu May 23 11:23:06 2024 daemon.err vnts[9845]:
Thu May 23 11:23:06 2024 daemon.err vnts[9845]: For more information try '--help'
Thu May 23 11:23:07 2024 daemon.err uhttpd[2236]: luci.util.pcdata() has been replaced by luci.xml.pcdata() - Please update your code.
Thu May 23 11:23:07 2024 daemon.err uhttpd[2236]: luci.util.pcdata() has been replaced by luci.xml.pcdata() - Please update your code.
Thu May 23 11:23:07 2024 daemon.err uhttpd[2236]: luci.util.pcdata() has been replaced by luci.xml.pcdata() - Please update your code.
Thu May 23 11:23:07 2024 daemon.err uhttpd[2236]: luci.util.pcdata() has been replaced by luci.xml.pcdata() - Please update your code.
Thu May 23 11:23:07 2024 daemon.err uhttpd[2236]: luci.util.pcdata() has been replaced by luci.xml.pcdata() - Please update your code.
Thu May 23 11:23:07 2024 daemon.err uhttpd[2236]: luci.util.pcdata() has been replaced by luci.xml.pcdata() - Please update your code.
Thu May 23 11:23:07 2024 daemon.err uhttpd[2236]: luci.util.pcdata() has been replaced by luci.xml.pcdata() - Please update your code.
Thu May 23 11:23:07 2024 daemon.err uhttpd[2236]: luci.util.pcdata() has been replaced by luci.xml.pcdata() - Please update your code.
Thu May 23 11:23:07 2024 daemon.err uhttpd[2236]: luci.util.pcdata() has been replaced by luci.xml.pcdata() - Please update your code.
Thu May 23 11:23:07 2024 daemon.err uhttpd[2236]: luci.util.pcdata() has been replaced by luci.xml.pcdata() - Please update your code.
Thu May 23 11:23:07 2024 daemon.err uhttpd[2236]: luci.util.pcdata() has been replaced by luci.xml.pcdata() - Please update your code.
Thu May 23 11:23:07 2024 daemon.err uhttpd[2236]: luci.util.pcdata() has been replaced by luci.xml.pcdata() - Please update your code.
Thu May 23 11:23:11 2024 daemon.info vnts[9924]: version: 1.2.9
Thu May 23 11:23:11 2024 daemon.info vnts[9924]: Serial: 2405071448-739
Thu May 23 11:23:11 2024 daemon.err vnts[9924]: error: Found argument '--web-port' which wasn't expected, or isn't valid in this context
Thu May 23 11:23:11 2024 daemon.err vnts[9924]:
Thu May 23 11:23:11 2024 daemon.err vnts[9924]: Usage: vnts <--port <PORT>|--white-token <WHITE_TOKEN>|--gateway <GATEWAY>|--netmask <NETMASK>|--finger|--log-path <LOG_PATH>>
Thu May 23 11:23:11 2024 daemon.err vnts[9924]:
Thu May 23 11:23:11 2024 daemon.err vnts[9924]: For more information try '--help'

**Comment by hkthomas** [comment]
CPU是Qualcomm Atheros AR9344

**Comment by lmq8267** [comment]
好的  想起来了   mips不支持web界面 我现在修改了脚本[/etc/init.d/vnt](https://github.com/lmq8267/luci-app-vnt/commit/17e86ab1247dfee372eee1f7ce2451e980857b01) 去掉了mips的web界面命令

**Comment by hkthomas** [comment]
感谢感谢。

**Comment by hkthomas** [comment]
正常了，谢谢佬。

**Comment by hkthomas** [comment]
佬，WEB管理的HTTP服务好像跑不起来，跟这段有没有关系。

Thu May 23 12:05:28 2024 daemon.err uhttpd[2236]: luci.util.pcdata() has been replaced by luci.xml.pcdata() - Please update your code.
Thu May 23 12:05:28 2024 daemon.err uhttpd[2236]: luci.util.pcdata() has been replaced by luci.xml.pcdata() - Please update your code.
Thu May 23 12:05:28 2024 daemon.err uhttpd[2236]: luci.util.pcdata() has been replaced by luci.xml.pcdata() - Please update your code.
Thu May 23 12:05:28 2024 daemon.err uhttpd[2236]: luci.util.pcdata() has been replaced by luci.xml.pcdata() - Please update your code.
Thu May 23 12:05:28 2024 daemon.err uhttpd[2236]: luci.util.pcdata() has been replaced by luci.xml.pcdata() - Please update your code.
Thu May 23 12:05:28 2024 daemon.err uhttpd[2236]: luci.util.pcdata() has been replaced by luci.xml.pcdata() - Please update your code.
Thu May 23 12:05:28 2024 daemon.err uhttpd[2236]: luci.util.pcdata() has been replaced by luci.xml.pcdata() - Please update your code.
Thu May 23 12:05:28 2024 daemon.err uhttpd[2236]: luci.util.pcdata() has been replaced by luci.xml.pcdata() - Please update your code.
Thu May 23 12:05:29 2024 daemon.err uhttpd[2236]: luci.util.pcdata() has been replaced by luci.xml.pcdata() - Please update your code.
Thu May 23 12:05:29 2024 daemon.err uhttpd[2236]: luci.util.pcdata() has been replaced by luci.xml.pcdata() - Please update your code.
Thu May 23 12:05:29 2024 daemon.err uhttpd[2236]: luci.util.pcdata() has been replaced by luci.xml.pcdata() - Please update your code.
Thu May 23 12:05:29 2024 daemon.err uhttpd[2236]: luci.util.pcdata() has been replaced by luci.xml.pcdata() - Please update your code.

**Comment by lmq8267** [comment]
不是  是vnts程序没有添加这个web功能 只有mips不支持

**Comment by hkthomas** [comment]
好的，了解。

**Comment by lmq8267** [comment]
> 佬，WEB管理的HTTP服务好像跑不起来，跟这段有没有关系。
> 
> Thu May 23 12:05:28 2024 daemon.err uhttpd[2236]: luci.util.pcdata() has been replaced by luci.xml.pcdata() - Please update your code. Thu May 23 12:05:28 2024 daemon.err uhttpd[2236]: luci.util.pcdata() has been replaced by luci.xml.pcdata() - Please update your code. Thu May 23 12:05:28 2024 daemon.err uhttpd[2236]: luci.util.pcdata() has been replaced by luci.xml.pcdata() - Please update your code. Thu May 23 12:05:28 2024 daemon.err uhttpd[2236]: luci.util.pcdata() has been replaced by luci.xml.pcdata() - Please update your code. Thu May 23 12:05:28 2024 daemon.err uhttpd[2236]: luci.util.pcdata() has been replaced by luci.xml.pcdata() - Please update your code. Thu May 23 12:05:28 2024 daemon.err uhttpd[2236]: luci.util.pcdata() has been replaced by luci.xml.pcdata() - Please update your code. Thu May 23 12:05:28 2024 daemon.err uhttpd[2236]: luci.util.pcdata() has been replaced by luci.xml.pcdata() - Please update your code. Thu May 23 12:05:28 2024 daemon.err uhttpd[2236]: luci.util.pcdata() has been replaced by luci.xml.pcdata() - Please update your code. Thu May 23 12:05:29 2024 daemon.err uhttpd[2236]: luci.util.pcdata() has been replaced by luci.xml.pcdata() - Please update your code. Thu May 23 12:05:29 2024 daemon.err uhttpd[2236]: luci.util.pcdata() has been replaced by luci.xml.pcdata() - Please update your code. Thu May 23 12:05:29 2024 daemon.err uhttpd[2236]: luci.util.pcdata() has been replaced by luci.xml.pcdata() - Please update your code. Thu May 23 12:05:29 2024 daemon.err uhttpd[2236]: luci.util.pcdata() has been replaced by luci.xml.pcdata() - Please update your code.

这个报错 可以自行修改  编辑/usr/lib/lua/luci/model/cbi/vnt.lua   编辑页面使用快捷指令 Ctrl 加 h   搜索util 替换为xml 即可，因为旧版openwrt不能用xml   所以我一直没有更新

**Comment by hkthomas** [comment]
好的谢谢。

**Comment by hkthomas** [comment]
佬，发现个新问题。

服务端日志显示这个。

公钥私钥留空或者有内容都是这样，手动去编缉/tmp/key/里面的两个文件会提示没权限，把两个文件删除重新上传有内容的，重启服务端之类的还是会留空。

x86跟AR9344测试都是这样子。

2024-05-23 15:21:12 vnt : 开始启动
2024-05-23 07:21:14 vnt: [src/cipher/rsa_cipher.rs:60] WARN vnts::cipher::rsa_cipher:保存私钥文件失败:PKCS#8 ASN.1 error: I/O error: FilesystemLoop
2024-05-23 07:21:14 vnt: [src/cipher/rsa_cipher.rs:69] WARN vnts::cipher::rsa_cipher:保存公钥文件失败:ASN.1 error: I/O error: FilesystemLoop
2024-05-23 07:21:14 vnt: [src/main.rs:256] INFO vnts:config:ConfigInfo { port: 2345, white_token: None, gateway: 10.26.0.1, broadcast: 10.26.0.255, netmask: 255.255.255.0, check_finger: false, username: "admin", password: "admin" }
2024-05-23 07:21:14 vnt: [src/main.rs:258] INFO vnts:监听udp端口: 2345
2024-05-23 07:21:14 vnt: [src/main.rs:261] INFO vnts:监听tcp端口: 2345
2024-05-23 07:21:14 vnt: [src/main.rs:266] INFO vnts:监听http端口: 7777
2024-05-23 07:21:14 vnt: [/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/actix-server-2.3.0/src/builder.rs:240] INFO actix_server::builder:starting 4 workers
2024-05-23 07:21:14 vnt: [/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/actix-server-2.3.0/src/server.rs:197] INFO actix_server::server:Tokio runtime found; starting in existing Tokio runtime
2024-05-23 07:21:16 vnt: [src/core/service/mod.rs:53] ERROR vnts::core::service:addr=[::ffff:221.225.45.61]:14097,Disconnect

**Comment by lmq8267** [comment]
辛苦加QQ群1034868233   问一下作者  这个我也不清楚怎么回事

**Comment by hkthomas** [comment]
我在这个群，原来一个作者啊，好的，我问问。

**Comment by hkthomas** [comment]
我在这个群，原来一个作者啊，好的，我问问。

**Comment by lmq8267** [comment]
我不是vnt的作者      这个问题我发现了，我修改一下 程序路径/tmp/vnts  就会出现这个情况   不是/tmp/vnts 就没问题

**Comment by hkthomas** [comment]
是的哥，我昨天改了下这个路径解决了。用默认的/tmp/key怎么都会失败。

**Comment by hkthomas** [comment]
好的哥。
